### ISSUE TITLE
Lots of issues 

### ISSUE THREAD

**Issue by polyinnovator** [vbeskrovnov/obsidian-contacts#7]
To be honest I could barely get this plugin to work. I tried multiple folder structures, and finally got it to accept the folder. I made sure the path was correct with / and everything.

None of my contacts are showing up on the side pane, two did for a split second then they disappeared. Although they were just empty boxes with no info showing up.

Sorry I can't describe it more, it is just nothing is working like it should. Maybe it is cause I have too big of an index? 5000 entries, but that shouldn't be the case I don't think for this plugin.

**Comment by vbeskrovnov** [comment]
Thank you for the feedback! Hope this fix will help. Please let me know if it doesn't
